# .streamlit/secrets.toml

[mysql]
host = ""
port = 3306
database = ""
user = ""
password = ""

# [mysql]
# host = "localhost"
# port = 3306
# database = "textile_362"
# user = "root"
# password = ""
