# .streamlit/secrets.toml

# [mysql]
# host = ""
# port = 3306
# database = ""
# user = ""
# password = ""

# [mysql]
# host = "localhost"
# port = 3306
# database = "textile_362"
# user = "root"
# password = ""

# .streamlit/secrets.toml

[mysql]
host = "db4free.net"
port = 3306
database = "textile_store"
user = "smsraj"
password = "deer@2001"
